jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cache Maven Repos
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        architecture: x64
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Print maven version
      run: mvn -version
    - continue-on-error: true
      name: Test Config
      run: mvn clean package -Pcit-test -e -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - continue-on-error: true
      name: Clean Env
      run: mvn clean -Premove-test-data -e -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - continue-on-error: true
      name: Test Naming
      run: mvn clean package -Pnit-test -e -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - continue-on-error: true
      name: Clean Env
      run: mvn clean -Premove-test-data -e -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    strategy:
      matrix:
        java:
        - 8
        - 8.0.192
        - 11
        - 11.0.3
        os:
        - ubuntu-latest
name: Integration Test
on:
  repository_dispatch:
    types: trigger-ga___it.yml
permissions:
  contents: read
